---
title: "Change Pchic Annotation"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
suppressPackageStartupMessages({
  library(dplyr)
  library(RCy3)
  library(data.table)
  library(GenomicRanges)
})

"%ni%" <- Negate("%in%")
```

```{r}
prepare_pchic <- function(cell_lines = "all", minimum_interaction = 5){
  load("DATA/pchic.RData")
  if (length(cell_lines) >= 1){
    cell_lines = c("Mon", "Mac0", "Mac1", "Mac2", "Neu", "MK", "EP", "Ery", "FoeT", "nCD4", "tCD4", "aCD4", "naCD4", "nCD8", "tCD8", "nB", "tB")
  }
  pchic <- data.frame(pchic[rowSums(pchic[,cell_lines] >= minimum_interaction) >= 1, 1:10]) %>% na.omit(.)
  colnames(pchic)[c(1:5, 6:10)] <- rep(c("chr", "start", "end", "ID", "Name"), 2)
  return(pchic)
}

Pchic_all_network <- prepare_pchic(cell_lines = "all")
pchic_bed <- unique(rbind(Pchic_all_network[, c(1:4, 5)], Pchic_all_network[, c(6:9, 10)]))
```

```{r}
library("GenomicRanges")
library("AnnotationHub")
library("rtracklayer")
library("Repitools")
```

```{r}
Ahub <- AnnotationHub()
Ahub <- subset(Ahub, species == "Homo sapiens")
unique(Ahub$dataprovider)

promoter_data <- query(Ahub, c("GRanges", "hg38"))
promoter_data$title

test <- promoter_data[["AH75192"]]
test2 <- promoters(test)
test3 <- annoGR2DF(test2)
```

```{r}
library(biomaRt)
mart<- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
refseq <- test3$name
geneSymbol <- getBM(filters="refseq_mrna", attributes=c("hgnc_symbol", "refseq_mrna"), values=refseq, mart=mart)

New_annotation <- merge(test3, geneSymbol, by.x = "name", by.y = "refseq_mrna", all.x = T, all.y = T)
New_annotation <- New_annotation[,-1]
New_annotation <- dplyr::select(New_annotation, chr:strand, hgnc_symbol) %>% unique(.) 
```

