---
title: "Chas_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())

suppressPackageStartupMessages({
  library(dplyr)
  library(chaser)
  library(stringr)
  library(biomaRt)
  library(gridExtra)
  library(grid)
  library(ggplot2)
})
source("~/Core_scripts/core_functions.R")
source("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Make_koichi_factor.R")
load("DATA/pchic.RData")
```

```{r}
prepare_pchic <- function(cell_lines = NULL, minimum_interaction = 5, pchic = NULL){
  if (is.null(pchic)){
    load("DATA/pchic.RData")
  }
  if (is.null(cell_lines)){
    cell_lines = c("Mon", "Mac0", "Mac1", "Mac2", "Neu", "MK", "EP", "Ery", "FoeT", "nCD4", "tCD4", "aCD4", "naCD4", "nCD8", "tCD8", "nB", "tB")
  }
  pchic <- data.frame(pchic[rowSums(pchic[,cell_lines] >= minimum_interaction) >= 1,c(1,2,3,6,7,8)]) %>% na.omit(.)
  return(pchic)
}

GE_fragments <- read.csv("/media/alexis/DATA/Chas_DATA/GE_fragments.csv", row.names=1, check.names = F)
Meth_fragments <- read.csv("/media/alexis/DATA/Chas_DATA/Meth_fragments.tsv", sep = "\t")
Pheno <- read.csv("/media/alexis/DATA/Koichi_methylation_dat/samplesheet.csv") %>% unique()
```

```{r}
pchic$baitChr <- paste0("chr", pchic$baitChr)
pchic$oeChr <- paste0("chr", pchic$oeChr)

all_cell_lines <- colnames(pchic)[12:28]

pchics <- lapply(all_cell_lines, function(cells){
  ps <- prepare_pchic(cells, pchic = pchic)
  chaser::make_chromnet(ps)
})
names(pchics) <- all_cell_lines
```

```{r}
chas_for_selected_pheno <- function(pchic = pchics, RNAseq = GE_fragments, DNA_met = Meth_fragments, pheno_ge, pheno_meth, title, cells){
  RNAseq <- RNAseq[,pheno_ge]
  DNA_meth <- DNA_met[,pheno_meth]
  
  pchics_pp <- lapply(names(pchics), function(cell_type){
    message(cell_type)
    baits <- export(pchics[[cell_type]], 'baits')
    pp <- chaser::subset_chromnet(pchics[[cell_type]], method = "nodes", nodes1 = baits)
    pp_exp <- chaser::load_features(pp,RNAseq,type='features_on_nodes',featnames = colnames(RNAseq), missingv=0)
    pp_exp_meth <- chaser::load_features(pp_exp,DNA_meth,type='features_tables',featnames = colnames(DNA_meth), missingv=0)
    chas <- chaser::chas(pp_exp_meth)
    chas_random <- tryCatch(chaser::randomize(pp_exp_meth, nrandom = 10, dist.match = T), error=function(e) NULL)
    chas_random <- lapply(chas_random, chaser::chas)
    feat <- chaser::export(pp_exp_meth)
    list("pp_exp" = pp_exp_meth, "chas" = chas, "rand" = chas_random, "feat" = feat)
  })
  names(pchics_pp) <- cells
  chas_cell_lines <- sapply(names(pchics_pp), function(cell_type){
    pchics_pp[[cell_type]][["chas"]]
  })
  message("Pchic_pp DONE!")
  chas_cell_lines_df <- data.frame(cell_lines = rep(cells, each = nrow(chas_cell_lines)),
                                   values = as.vector(chas_cell_lines))
  
  p <- ggplot2::ggplot(chas_cell_lines_df, aes(x = cell_lines, y = values, fill = cell_lines))
  p <- p + ggplot2::geom_violin()
  p <- p + theme(axis.line = element_line(colour = "black"),
                 axis.text.x=element_text(size=16),
                 axis.text.y=element_text(size=16),
                 axis.title.x=element_text(size=16),
                 axis.title.y=element_text(size=16))
  p <- p + ggplot2::geom_jitter()
  p <- p + ggtitle(title)
  
  list("plot" = p,
       "pchics_pp" = pchics_pp)
}
```


```{r}
Factor_R_OR_NR_B_met <- sapply(colnames(Meth_fragments)[4:108], function(phen){
  Pheno[which(Pheno$Sample == phen), "Pheno"][1]
}) 

Factor_R_OR_NR_B_met <- ifelse(stringr::str_detect(Factor_R_OR_NR_B_met, pattern = "Baseline.CR."), "R.B", 
              ifelse(stringr::str_detect(Factor_R_OR_NR_B_met, pattern = "Baseline.SD"), "NR.B", 
                     ifelse(stringr::str_detect(Factor_R_OR_NR_B_met, pattern = "Post_treatment"), "REL", "OR"))) %>% as.factor()


Pheno_met_chas <- lapply(levels(Factor_R_OR_NR_B_met), function(pheno){
  ref_meth <- c(T, T, T)
  ref_meth <- c(ref_meth, Factor_R_OR_NR_B_met == pheno)
  ref_meth <- c(ref_meth[1:97], rep(F, 8))
  
  ref_ge <- Factor_R_OR_NR_B == pheno
  
  chas_for_selected_pheno(pchic = pchics, RNAseq = GE_fragments, DNA_met = Meth_fragments, pheno_ge = ref_ge, pheno_meth = ref_meth, title = pheno, cells = all_cell_lines)
})
names(Pheno_met_chas) <- levels(Factor_R_OR_NR_B_met)
```

