---
title: "Functional Protein Protein Interaction layer"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
suppressPackageStartupMessages({
  library(dplyr)
  library(RCy3)
  library(igraph)
  library(data.table)
  library(stringr)
})

"%ni%" <- Negate("%in%")
```

### DATA

```{r}
Diff_Prot_exp <- read.csv("Results/Proteo/Diff_Prot_exp.tsv", sep = "\t", check.names = F)

Diff_Prot_exp_filtered_Mut_vs_CD34 <- dplyr::filter(Diff_Prot_exp, Mutations_of_interest_vs_CD34_significant) %>% dplyr::select(c("name":"ID", "Mutations_of_interest_vs_CD34_CI.L":"Mutations_of_interest_vs_CD34_p.val", "Mutations_of_interest_vs_CD34_significant"))

PPI_base <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")

colnames(PPI_base) <- c("source", "target", "Annotation", "Direction", "Score")

PPI_filtered <- dplyr::filter(PPI_base, source %in% Diff_Prot_exp_filtered_Mut_vs_CD34$name | target %in% Diff_Prot_exp_filtered_Mut_vs_CD34$name)
```

```{r}
write.table(PPI_filtered, "Results/Proteo/fPPI_network.tsv", sep = "\t", row.names = F)
```

