---
title: "GEM_network"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

%%%%%%%%%%%%% INITIALISATION & PACKAGES %%%%%%%%%%%%%

```{r}
rm(list = ls())

suppressPackageStartupMessages({
  library(dplyr)
  library(matrixTests)
})
```

%%%%%%%%%%%%% LOADING DATA %%%%%%%%%%%%%

%%%%%%%%%%%%% Making the metabolic network %%%%%%%%%%%%% 

```{r}
Human_GEM <- read.csv("DATA_Reactions/Human_GEM_2.csv")

Metabo_reactions <- stringr::str_split(Human_GEM$EQUATION, pattern = "\\+ | => | <=>")

names(Metabo_reactions) <- Human_GEM$ID

Metabolic_network <- lapply(names(Metabo_reactions), function(reaction){
  purrr::reduce(.f = function(a, b) rbind(a, data.frame(A = reaction, B = b)), .x = Metabo_reactions[[reaction]], .init = data.frame(A  = reaction, B = Metabo_reactions[[reaction]][1]))[-1,]
}) %>% purrr::reduce(.f = rbind, .x=.)

Metabolic_network_clean <- dplyr::filter(Metabolic_network, B != "")

Metabolic_network_clean$B <- stringr::str_trim(Metabolic_network_clean$B)

Remove_coeff <- function(metab){
  if(length(metab) > 1){
    ifelse(stringr::str_detect(metab[1], pattern = "[:alpha:]"), Reduce(x=metab, f = paste), Reduce(x=metab[-1], f = paste))
  }else{
    metab
  }
}

Metabolic_network_clean$B <- sapply(Metabolic_network_clean$B, function(metabolite){
  stringr::str_split(metabolite, pattern = "[:space:]") %>% .[[1]] %>% Remove_coeff()
})

Metabolic_network_clean <- unique(Metabolic_network_clean)

write.table(Metabolic_network_clean, "DATA_Reactions/Metabolic_network_clean.tsv", sep = "\t", row.names = F, quote = F)
```

%%%%%%%%%%%%% LOADING Reaction enriched %%%%%%%%%%%%% 

```{r}
mIDHi_react_scores_GEM <- read.csv("DATA_Reactions/mIDHi_react_scores_GEM.csv", check.names = F, row.names = 1)
colnames(mIDHi_react_scores_GEM) <- colnames(mIDHi_react_scores_GEM) %>% 
  stringr::str_remove("X")

```

```{r}
Clinical_patient_data <- read.csv("~/GitHub/Koichi_gene_expression_analyses_git/Koichi_gene_expression_analyses/DATA/Clinical_patient_data.csv") %>%
  .[!duplicated(.),]

Make_factor <- function(Samplesheet = Clinical_patient_data,
                        Samples_names,
                        Mutations_to_ignore = 0,
                        Clinical_outcome_A,
                        Clinical_name_A,
                        Clinical_outcome_B,
                        Clinical_name_B,
                        Clinical_outcome_C,
                        Clinical_name_C){
  if(typeof(Mutations_to_ignore) != "double"){
    Mutations_samples <- Samplesheet[which(duplicated(str_split(Samplesheet$mutations, pattern=","), Mutations_to_ignore)),] %>%
      c(.$Baseline_RNAseq_data, .$Relapse_RNAseq_data) %>%
      na.omit()
    Mutations_factor <- factor(ifelse(Samples_names %in% Mutations_samples, "Mut", "WT"))
  }else{
    Mutations_factor <- factor(rep("", length(Samples_names)))
  }

  Clinical_outcome_A <- Samplesheet[which(Samplesheet$Best_response %in% Clinical_outcome_A),] %>%
    c(.$Baseline_RNAseq_data, .$Relapse_RNAseq_data) %>%
    na.omit()
  Clinical_outcome_B <- Samplesheet[which(Samplesheet$Best_response %in% Clinical_outcome_B),] %>%
    c(.$Baseline_RNAseq_data, .$Relapse_RNAseq_data) %>%
    na.omit()
  Clinical_outcome_C <- Samplesheet[which(Samplesheet$Best_response %in% Clinical_outcome_C),] %>%
    c(.$Baseline_RNAseq_data, .$Relapse_RNAseq_data) %>%
    na.omit()

  Clinical_outcome <- factor(ifelse(Samples_names %in% Clinical_outcome_A, Clinical_name_A,
                                    ifelse(Samples_names %in% Clinical_outcome_B, Clinical_name_B,
                                           ifelse(Samples_names %in% Clinical_outcome_C, Clinical_name_C, ""))))
  Sample_timing <- factor(ifelse(Samples_names %in% Samplesheet$Baseline_RNAseq_data, "B", "REL"))
  if(typeof(Mutations_to_ignore) != "double"){
    Final_factor <- paste(Mutations_factor, Clinical_outcome, Sample_timing, sep = ".") %>% as.factor()
  }else{
    Final_factor <- paste(Clinical_outcome, Sample_timing, sep = ".") %>% as.factor()
  }

  return(Final_factor)
}

Factor_R_OR_NR_B <- Make_factor(Clinical_patient_data,
                                colnames(mIDHi_react_scores_GEM),
                                0,
                                c("CR", "CRi"),
                                "R",
                                c("MLFS", "HI", "CRp", "PR"),
                                "OR",
                                c("SD", "PD"),
                                "NR")
```

```{r}
t_test_pheno_comp <- function(pheno_df, phenoA, phenoB, df){
  res <- row_t_welch(df[, pheno_df == phenoA], df[, pheno_df == phenoB]) %>%
    dplyr::filter(pvalue < 0.05) %>%
    t()
  colnames(res) <- stringr::str_remove(colnames(res), pattern = "_pos")
  colnames(res) <- stringr::str_remove(colnames(res), pattern = "_neg")
  
  res[,!duplicated(colnames(res))] %>% t()
}
```


```{r}
NR_R_T_test <- t_test_pheno_comp(Factor_R_OR_NR_B, "NR.B", "R.B", mIDHi_react_scores_GEM)

Factor_relapse <- as.vector(Factor_R_OR_NR_B)
Factor_relapse[Factor_relapse == "OR.REL" | Factor_relapse == "R.REL"] <- "REL"

REL_R_T_test <- t_test_pheno_comp(Factor_relapse, "REL", "R.B", mIDHi_react_scores_GEM)

REL_NR_T_test <- t_test_pheno_comp(Factor_relapse, "REL", "NR.B", mIDHi_react_scores_GEM)
```

```{r}
write.csv(NR_R_T_test, "DATA_Reactions/NR_R_T_test.csv")
write.csv(REL_R_T_test, "DATA_Reactions/REL_R_T_test.csv")
write.csv(REL_NR_T_test, "DATA_Reactions/REL_NR_T_test.csv")
```

```{r}
library(biomaRt)

Gene_to_convert <- Human_GEM$GENE.ASSOCIATION %>% stringr::str_split(pattern = " or ") %>% unlist() %>% unique()

ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
genes_annotated <- getBM(attributes = c('hgnc_symbol', 'ensembl_gene_id'), filters = 'ensembl_gene_id', values = Gene_to_convert, mart = ensembl)
```

```{r}
Reaction_Gene_asso <- Human_GEM[,c(1,4)]

Gene_reactions <- stringr::str_split(Reaction_Gene_asso$GENE.ASSOCIATION, pattern = " or ")

names(Gene_reactions) <- Human_GEM$ID

Gene_converter <- genes_annotated$hgnc_symbol
names(Gene_converter) <- genes_annotated$ensembl_gene_id

Gene_reactions <- lapply(Gene_reactions, function(reaction){
  sapply(reaction, function(gene){
    Gene_converter[gene]
  }) %>% unique()
})
```

```{r}
Gene_reactions_network <- lapply(names(Gene_reactions), function(reaction){
  purrr::reduce(.f = function(a, b) rbind(a, data.frame(A = reaction, B = b)), .x = Gene_reactions[[reaction]], .init = data.frame(A  = reaction, B = Gene_reactions[[reaction]][1]))[-1,]
}) %>% purrr::reduce(.f = rbind, .x=.)

Gene_reactions_network_cleaned <- na.omit(Gene_reactions_network)
Gene_reactions_network_cleaned <- dplyr::filter(Gene_reactions_network_cleaned, B != "")

Gene_reactions_network_cleaned_filtered <- Gene_reactions_network_cleaned[Gene_reactions_network_cleaned$A %in% rownames(NR_R_T_test),]

write.table(Gene_reactions_network_cleaned_filtered, "Results/Metabolic_network/Gene_reactions_network.tsv", sep = "\t", row.names = F, quote = F)
write.table(NR_R_T_test, "Results/Metabolic_network/Metabolic_features.tsv", sep = "\t", quote = F)

Metabolic_network_clean_NR_R <- dplyr::filter(Metabolic_network_clean, A %in% rownames(NR_R_T_test))
write.table(Metabolic_network_clean_NR_R, "Results/Metabolic_network/Metabolic_network_clean_NR_R.tsv", sep = "\t", row.names = F, quote = F)
```













```{r}
Gene_reaction_net <- read.table("Results/Metabolic_network/Gene_reactions_network.tsv", sep = "\t", header = F)
Metabolic_network <- read.table("Results/Metabolic_network/Metabolic_network_clean_NR_R.tsv", sep =  "\t", header = F)

Interconnect_all_node_from_vector <- function(vec){
  len <- length(vec)
  source <- sapply(1:len, function(element){
    rep(vec[element], len-element)
  }) %>% unlist()
  target <- sapply(1:(len-1), function(element){
    vec[(1+element):len]
  }) %>% unlist()
  data.frame("V1" = source,
             "V2" = target)
}

Replace_reactions_to_gene_names <- function(metabo_net, reaction_gene_annotation){
  res <- lapply(1:nrow(metabo_net), function(n_row){
    reaction_A_gene <- dplyr::filter(reaction_gene_annotation, V1 == metabo_net[n_row, "V1"]) %>% .$V2
    if (length(reaction_A_gene) == 0){
      reaction_A_gene <- metabo_net[n_row, "V1"]
    }
    reaction_B_gene <- dplyr::filter(reaction_gene_annotation, V1 == metabo_net[n_row, "V2"]) %>% .$V2
    if (length(reaction_B_gene) == 0){
      reaction_B_gene <- metabo_net[n_row, "V2"]
    }
    vec <- unique(c(reaction_A_gene, reaction_B_gene))
    
    if(n_row %% floor(nrow(metabo_net)/100) == 0){
      message(paste0(n_row %/% floor(nrow(metabo_net)/100), "%!"))
    }
    if(length(vec) == 1){
      data.frame("V1" = metabo_net[n_row, "V1"], "V2"= metabo_net[n_row, "V2"])
    }else{
      Interconnect_all_node_from_vector(vec)
    }
  })

  res <- data.table::rbindlist(res)
  unique(res)
}

```

```{r}
Gene_metabolite_network <- Replace_reactions_to_gene_names(Metabolic_network, Gene_reaction_net)

write.table(Gene_metabolite_network, "Results/Metabolic_network/Gene_metabolite_network_converted.tsv", sep = "\t", row.names = F, quote = F, col.names = F)
```

```{r}
Metabolic_network_all <- read.table("/home/alexis/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/DATA_Reactions/Metabolic_network_clean.tsv", sep = "\t", header = T)
colnames(Metabolic_network_all) <- c("V1", "V2")
Gene_reaction_converter <- read.table("/home/alexis/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/DATA_Reactions/Gene_reactions_network_cleaned.csv", sep = ",", header = T, row.names = 1)
colnames(Gene_reaction_converter) <- c("V1", "V2")
```


```{r}
Gene_metabolite_all_network <- Replace_reactions_to_gene_names(Metabolic_network_all, Gene_reaction_converter)


```






