---
title: "Layer analyses"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
suppressPackageStartupMessages({
  library(dplyr)
  library(RCy3)
  library(igraph)
  library(data.table)
  library(stringr)
  library(clusterProfiler)
  library(ggplot2)
  library(grid)
  library(ggraph)
  library(RColorBrewer)
  library(viridis)
})

"%ni%" <- Negate("%in%")
```


```{r}
Pchic_layer <- read.table("MuxViz_multiplex/Multiplex_DNA_methylation_function.edges", sep = " ", header = F)
Pchic_layer_igraph <- igraph::graph_from_data_frame(Pchic_layer)
eigen <- eigen_centrality(Pchic_layer_igraph)
Layout <- read.table("MuxViz_multiplex/Multiplex_function_layout.txt", header = T, sep = " ")
Layout <- merge(Layout, eigen$vector, by.x = "nodeID", by.y = 0, all.x = T)
colnames(Layout)[16] <- "eigen_pchic"
Layout_pchic <- Layout %>%
  dplyr::filter(!is.na(eigen_pchic))

write.table(Layout_pchic, "Results/Layer_analyses/Pchic_notfiltered_features.tsv", sep = "\t", quote=F, row.names = F)
```

