---
title: "Multi_layer_network_supra_adjacency_matrix"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---


```{r}
rm(list = ls())

suppressPackageStartupMessages({
  library(dplyr)
  library(igraph)
  library(ggvenn)
})
```

LOADING LAYERS OF THE MULTI-LAYER NETWORK

```{r}
Pchic_all_network <- read.table("Results/Pchic/Promoter_fragment_all_pchic.tsv", sep = "\t", header = T)
fPPI <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")
colnames(fPPI) <- c("source", "target", "Annotation", "Direction", "Score")
Metabolic_all_network <- 
```


```{r}
Pchic_layer <- read.table("Results/Pchic/Promoter_fragment_cleaned.tsv", sep = "\t", header = T)
GRN_layer <- read.table("Results/GRN/GRN_NR_R.tsv", sep = "\t")
PPI_layer <- read.table("Results/Proteo/fPPI_network_filtered.tsv", sep = "\t", header = T)
Metabolic_layer <- read.csv("Results/Metabolic_network/Gene_metabolite_network_converted.tsv", sep = "\t", header = F)
```

## Test overlaps

```{r}
VennDiagram_dat <- list(Chromatin_layer = unique(Pchic_layer$source, Pchic_layer$target),
                        GRN_layer = unique(GRN_layer$V1, GRN_layer$V2),
                        PPI_layer = unique(PPI_layer$source, PPI_layer$target), 
                        Metabolic_layer = unique(Metabolic_layer$V1, Metabolic_layer$V2)
                        )

ggvenn(
  VennDiagram_dat, 
  stroke_size = 0.5, set_name_size = 4
  )
```

Make_combined_network

Chromatin layer

```{r}
Chromatine_layer_nodes <- unique(Pchic_layer$source, Pchic_layer$target) %>% intersect(unique(GRN_layer$V1, GRN_layer$V2))
Chromatine_layer_nodes <- unique(Pchic_layer$source, Pchic_layer$target) %>% intersect(unique(Metabolic_layer$V1, Metabolic_layer$V2)) %>% c(., Chromatine_layer_nodes) %>% unique()

Chromatine_layer_focus <- Pchic_layer %>% dplyr::filter(.$source %in% Chromatine_layer_nodes | .$target %in% Chromatine_layer_nodes)
colnames(Chromatine_layer_focus) <- c("source", "target")
```

GRN layer

```{r}
GRN_layer_nodes <- unique(GRN_layer$V1, GRN_layer$V2) %>% intersect(unique(PPI_layer$source, PPI_layer$target))
GRN_layer_nodes <- unique(GRN_layer$V1, GRN_layer$V2) %>% intersect(unique(Pchic_layer$source, Pchic_layer$target)) %>% c(., GRN_layer_nodes) %>% unique()

GRN_layer_focus <- GRN_layer %>% dplyr::filter(.$V1 %in% GRN_layer_nodes | .$V2 %in% GRN_layer_nodes) %>% .[,1:2]
colnames(GRN_layer_focus) <- c("source", "target")
```

PPI_layer

```{r}
PPI_layer_nodes <- unique(PPI_layer$source, PPI_layer$target) %>% intersect(unique(Metabolic_layer$V1, Metabolic_layer$V2))
PPI_layer_nodes <- unique(PPI_layer$source, PPI_layer$target) %>% intersect(unique(GRN_layer$V1, GRN_layer$V2)) %>% c(., PPI_layer_nodes) %>% unique()

PPI_layer_focus <- PPI_layer %>% dplyr::filter(.$source %in% PPI_layer_nodes | .$target %in% PPI_layer_nodes) %>% .[,1:2]
colnames(PPI_layer_focus) <- c("source", "target")
```

```{r}
Metabolic_layer_nodes <- unique(Metabolic_layer$V1, Metabolic_layer$V2) %>% intersect(unique(PPI_layer$source, PPI_layer$target))
Metabolic_layer_nodes <- unique(Metabolic_layer$V1, Metabolic_layer$V2) %>% intersect(unique(Pchic_layer$source, Pchic_layer$target)) %>% c(., Metabolic_layer_nodes) %>% unique()

Metabolic_layer_focus <- Metabolic_layer %>% dplyr::filter(.$V1 %in% Metabolic_layer_nodes | .$V2 %in% Metabolic_layer_nodes)
colnames(Metabolic_layer_focus) <- c("source", "target")
```

```{r}
Combined_network <- list(Chromatine_layer_focus, GRN_layer_focus, PPI_layer_focus, Metabolic_layer_focus)
Combined_network <- Combined_network %>% purrr::reduce(rbind) %>% unique()

Combined_network %>% write.table("Results/Combined_network.tsv", sep = "\t", quote = F, row.names = F)
```

