---
title: "muxViz"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
suppressPackageStartupMessages({
  library(dplyr)
  library(RCy3)
  library(igraph)
  library(data.table)
  library(stringr)
  library(clusterProfiler)
  library(ggplot2)
  library(muxViz)
  library(grid)
  library(ggraph)
  library(RColorBrewer)
  library(viridis)
})

"%ni%" <- Negate("%in%")
```

### Function

```{r}
Add_layer <- function(network_path, separateur = "\t", features_path, separateur_feat = "\t", config_path, title_network, title_multiplex){
  layer_config <- paste0(getwd(), "/MuxViz_multiplex/Multiplex_", title_network, ".edges;", title_network, ";", getwd(), "/MuxViz_multiplex/Multiplex_", title_multiplex, "_layout.txt")
  net <- read.table(network_path, sep = separateur, check.names = F, header = T)
  colnames(net)[1:2] <- c("source", "target")
  layout <- data.frame(nodeID = c(net$source, net$target) %>% unique())
  layout$nodeLabel <- layout$nodeID
  if(!file.exists(config_path)){
    layer_config_file <- data.frame(V1 = layer_config)
    layout_file <- layout
  }else{
    layer_config <- data.frame(V1 = layer_config)
    layer_config_file <- read.table(config_path, sep = ",", header = F, check.names = F)
    layer_config_file <- rbind(layer_config_file, layer_config)
    layout_file <- read.table(paste0(getwd(), "/MuxViz_multiplex/Multiplex_", title_multiplex, "_layout.txt"), sep = " ", header = T, check.names = F)
    layout_file <- merge(layout_file, layout, by.x = "nodeID", by.y = colnames(layout)[1], all.x = T, all.y = T) %>%
      .[!duplicated(.$nodeID),]
  }
  write.table(layer_config_file, config_path, row.names = F, col.names = F, quote = F)
  if(!is.na(features_path)){
    feat <- read.table(features_path, sep = separateur_feat, check.names = F, header = T)
    colnames(feat)[-1] <- paste0(title_network, "_", colnames(feat)[-1])
  }else{
    feat <- data.frame("name" = layout$nodeID)
  }
  layout_file <- merge(layout_file, feat, by.x = "nodeID", by.y = colnames(feat)[1], all.x = T, all.y = T)
  if("nodeLabel.y" %in% colnames(layout_file)){
    layout_file <- layout_file[,colnames(layout_file) != "nodeLabel.y" & colnames(layout_file) != "nodeLabel.x."]
    colnames(layout_file)[2] <- "nodeLabel"
  }
  layout_file$nodeLabel <- layout_file$nodeID
  write.table(layout_file, paste0(getwd(), "/MuxViz_multiplex/Multiplex_", title_multiplex, "_layout.txt"), sep = " ", row.names = F, col.names = T, quote = F)
  if(ncol(net) < 3){
    net$weight <- rep(1, nrow(net))
  }
  write.table(net, paste0(getwd(), "/MuxViz_multiplex/Multiplex_", title_network, ".edges"), sep = " ", col.names = F, row.names = F, quote = F)
}

Clean_missing_values <- function(feature_data_path, column2correct, final_value){
  df <- read.table(feature_data_path, sep = " ", header = T, check.names = F)
  if(final_value != "mini"){
    for (i in column2correct){
      data.table::set(df, which(is.na(df[[i]])), i, final_value)
    }
  }else{
    for (i in column2correct){
      minimum <- min(na.omit(df[[i]]))
      data.table::set(df, which(is.na(df[[i]])), i, minimum)
    }
  }
  write.table(df, feature_data_path, sep = " ", row.names = F, quote = F)
}

Transform_nodeLabelID2nodeID <- function(config_path){
  config_file <- read.table(config_path, sep = ";", header = F)
  layout_path <- config_file[1,3]
  layout_file <- read.table(layout_path, sep = " ", header = T, check.names = F)
  layout_file$nodeID <- rownames(layout_file)
  layout_file$nodeLabel <- sapply(layout_file$nodeLabel, function(label){
    if(stringr::str_detect(label, pattern = "[:alpha:]")){
      label
    }else{
      paste("frag", label, sep = "_")
    }
  })
  write.table(layout_file, layout_path, sep = " ", quote = F, col.names = T, row.names = F)
  layout_file <- layout_file[,1:2]
  sapply(config_file[[1]], function(edges_path){
    edges <- read.table(edges_path, sep = " ", header = F, check.names = F)
    edges$V1 <- sapply(edges$V1, function(label){
      if(stringr::str_detect(label, pattern = "[:alpha:]")){
        label
      }else{
        paste("frag", label, sep = "_")
      }
    })
    edges$V2 <- sapply(edges$V2, function(label){
      if(stringr::str_detect(label, pattern = "[:alpha:]")){
        label
      }else{
        paste("frag", label, sep = "_")
      }
    })
    edges <- merge(edges, layout_file, by.x = "V1", by.y = "nodeLabel", all.x = T)
    colnames(edges)[4] <- "source"
    edges <- merge(edges, layout_file, by.x = "V2", by.y = "nodeLabel", all.x = T)
    colnames(edges)[5] <- "target"
    edges <- dplyr::select(edges, "source", "target", "V3")
    write.table(edges, edges_path, sep = " ", row.names = F, col.names = F, quote = F)
  })
}
```


```{r}
Add_layer(network_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Layers/pchic_network.gr", 
          separateur = ",", 
          features_path = "Results/Pchic/pchic_NR_R_meth_features_promoter_fragments_features.tsv", 
          separateur_feat = "\t",
          config_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt", 
          title_network = "DNA_methylation", 
          title_multiplex = "function")

Add_layer(network_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Layers/GRN.gr", 
          separateur = "\t",
          features_path = "Results/GRN/Network_All_samples_features_for_muxviz.tsv", 
          separateur_feat = "\t",
          config_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt", 
          title_network = "GRN", 
          title_multiplex = "function")

Add_layer(network_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Layers/PPI_layer.gr", 
          separateur = ",", 
          features_path = "Results/Proteo/Diff_Prot_exp.tsv", 
          separateur_feat = "\t", 
          config_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt", 
          title_network = "fPPI", 
          title_multiplex = "function")

Add_layer(network_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Layers/Gene_reaction.gr", 
          separateur = ",",
          features_path = NA, 
          separateur_feat = NA, 
          config_path =  "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt", 
          title_network = "Gene_reaction", 
          title_multiplex = "function")

Add_layer(network_path = "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Layers/Metabo_reactions.gr", 
          separateur = "\t",
          features_path = "Results/Metabolic_network/NR_R_T_test.tsv", 
          separateur_feat = "\t", 
          config_path =  "~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt", 
          title_network = "Metabo", 
          title_multiplex = "function")

Clean_missing_values("MuxViz_multiplex/Multiplex_function_layout.txt", c("DNA_methylation_logFC", "GRN_logFC", "GRN_size", "GRN_nes", "fPPI_Mutations_of_interest_vs_Group_control_diff", "Metabo_mean.diff"), 0)
Clean_missing_values("MuxViz_multiplex/Multiplex_function_layout.txt", c("DNA_methylation_P.Value", "GRN_P.Value", "GRN_pval", "fPPI_Mutations_of_interest_vs_Group_control_p.val", "Metabo_pvalue"), 1)
Clean_missing_values("MuxViz_multiplex/Multiplex_function_layout.txt", c("GRN_eigenvalue", "GRN_Page_Rank"), "mini")

Transform_nodeLabelID2nodeID("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/MuxViz_multiplex/Multiplex_function_config.txt")
```


```{r}
Multiplex_test <- buildMultilayerNetworkFromMuxvizFiles(config.file = "MuxViz_multiplex/Multiplex_function_config.txt", MultisliceType = "categorical", isWeighted = T, isDirected = T, verbose = T)
```

```{r}
layer.colors <- c("#896944", "#FF0000", "#0000FF", "#008800", "#00FF00")
lay <- layoutMultiplex(Multiplex_test$g.list, layout="fr", ggplot.format=F, box=T)
plot_multiplex3D(g.list = Multiplex_test$g.list, layer.layout = lay, layer.colors = layer.colors, layer.space = 2, layer.labels.cex = 1.5 , node.size.scale = 0.8, show.aggregate = T)

snapshot3d("Results/multiplex.png", fmt = "png", width = 1024, height = 1024)
```


```{r}
pathInfomap <- "~/Test_Git/mux/muxViz/src-exe/infomap-0.x/Infomap"

commResult <- GetMultiplexCommunities_Infomap(Multiplex_test$g.list,
                                              bin.path=pathInfomap,
                                              isDirected=T,
                                              seed=12345,
                                              includeSelfLinks=F,
                                              numTrials=100,
                                              twoLevel=T,
                                              preclusterMultiplex=F,
                                              addMissingPhysicalNodes=F,
                                              hardPartitions=F,
                                              verbose=T,
                                              addAggregateAnalysis=T,
                                              multilayerRelaxRate=0.5,
                                              multilayerJSRelaxRate=NA,
                                              outputPrefix="multimap")

commResult.hp <- GetMultiplexCommunities_Infomap(Multiplex_test$g.list,
                                              bin.path=pathInfomap,
                                              isDirected=T,
                                              seed=12345,
                                              includeSelfLinks=F,
                                              numTrials=100,
                                              twoLevel=T,
                                              preclusterMultiplex=F,
                                              addMissingPhysicalNodes=F,
                                              hardPartitions=T,
                                              verbose=T,
                                              addAggregateAnalysis=T,
                                              multilayerRelaxRate=0.5,
                                              multilayerJSRelaxRate=NA,
                                              outputPrefix="multimap_hp")

```

```{r}
VI <- igraph::compare(commResult$membership.multi$module, commResult.hp$membership.multi$module, method="vi")
NMI <- igraph::compare(commResult$membership.multi$module, commResult.hp$membership.multi$module, method="nmi")
ARI <- igraph::compare(commResult$membership.multi$module, commResult.hp$membership.multi$module, method="adjusted.rand")
```

```{r}
pal.mux <- sample(viridis(commResult$modules.multi))
pal.aggr <- sample(viridis(commResult$modules.aggr))

png("Results/multi_sbm_infomap_table.png", width = 1024, height = 728 / 2,
    res = 100)
gplt <- plot_multimodules(commResult, module.colors = pal.mux,
                          show.aggregate = T)
dev.off()
#> agg_png 
#>       2
png("Results/multi_sbm_infomap_hp_table.png", width = 1024,
    height = 728 / 2, res = 100)
gplt.hp <- plot_multimodules(commResult.hp, module.colors = pal.mux,
                             show.aggregate = T)
dev.off()
```

```{r}
# coloring state nodes
Nodes <- 26327
Layers <- 5
node.colors.matrix <- matrix("#dadada", Nodes, Layers)
for (l in 1:Layers) {
    dftmp <- commResult$membership.multi[commResult$membership.multi$layer==l,]
    idxs <- dftmp$node
    node.colors.matrix[idxs,l] <- pal.mux[dftmp$module]
}

# coloring physical nodes in the aggregate
node.colors.aggr <- rep("#dadada", Nodes)
node.colors.aggr[commResult$membership.aggr$node] <- pal.aggr[commResult$membership.aggr$module]

plot_multiplex3D(Multiplex_test$g.list, layer.layout=lay, layer.colors=layer.colors,
                         layer.shift.x=0.5, layer.space=2,
                         layer.labels="auto", layer.labels.cex=1.5,
                         node.size.values="auto", node.size.scale=0.8,
                         node.colors=node.colors.matrix, edge.colors="#dadada",
                         node.colors.aggr=node.colors.aggr,
                         show.aggregate=T)
rgl::snapshot3d("Results/multi_sbm_infomap.png", fmt = "png", width = 1024, height = 1024)
#> Warning in snapshot3d("man/figures/multi_sbm_infomap.png", fmt = "png", :
#> webshot = TRUE requires the webshot2 package; using rgl.snapshot() instead
#> Warning in rgl.snapshot(filename, fmt, top): RGL: Pixmap save: unable to open
#> file 'man/figures/multi_sbm_infomap.png' for writing
#> Warning in rgl.snapshot(filename, fmt, top): 'rgl.snapshot' failed
```

```{r}
M <- BuildSupraAdjacencyMatrixFromEdgeColoredMatrices(Multiplex_test$nodeTensor, Multiplex_test$layerTensor, Layers, Nodes)
```


```{r}
GetMultilayerCommunities_Infomap_modified <- function(SupraAdjacencyMatrix,
           Layers,
           Nodes,
           bin.path = NA,
           isDirected,
           seed = 12345,
           includeSelfLinks = F,
           numTrials = 100,
           twoLevel = T,
           preclusterMultiplex = F,
           addMissingPhysicalNodes = T,
           hardPartitions = F,
           verbose = T,
           addAggregateAnalysis = T,
           outputPrefix = "multimap") {
    #

    if (is.na(bin.path) || !file.exists(bin.path)) {
      stop(
        "Error! You must provide a valid path to the INFOMAP bin.
        Likely you will find it in the bin/ folder of muxviz, or you must compile it from
        source in src/ folder. If this is the case, just unzip the infomap archive and
        run make that will generate executable Infomap.
        Feel free to move the file where you prefer and provide the full path as an
        argument to this function."
      )
    }

    tmpname <- outputPrefix
    inputFile <- paste0(tmpname, "_infomap.edges")
    if (file.exists(inputFile))
      file.remove(inputFile)
    fileConn <- file(inputFile, open = "at")

    cat('1/2 Setting up the algorithms...\n')

    # obtain an extended edgelist representation in format:
    # node.from layer.from node.to layer.to weight
    multilayerEdges <- BuildExtendedEdgelistFromSupraAdjacencyMatrix(
                         SupraAdjacencyMatrix,
                         Layers,
                         Nodes,
                         FALSE
                       )

    # write in the Infomap multilayer format for general multilayer networks
    # this part is different from the one in GetMultiplexCommunities_Infomap

    writeLines(c("*Intra", "#layer node node weight"), fileConn)
    mergedEdgelist <- data.frame()

    submulti <-
      multilayerEdges[multilayerEdges$layer.from == multilayerEdges$layer.to,]
    mergedEdgelist <-
      rbind(
        mergedEdgelist,
        data.frame(
          layer = submulti$layer.from,
          from = submulti$node.from,
          to = submulti$node.to,
          weight = submulti$weight
        )
      )
    if (!isDirected) {
      #this is because multimap requires both directions specified, even for undirected networks
      mergedEdgelist <-
        rbind(
          mergedEdgelist,
          data.frame(
            layer = submulti$layer.from,
            from = submulti$node.to,
            to = submulti$node.from,
            weight = submulti$weight
          )
        )
    }
    utils::write.table(
      mergedEdgelist,
      file = fileConn,
      row.names = F,
      col.names = F,
      quote = F
    )

    writeLines(c("*Inter", "#layer node layer weight"), fileConn)
    mergedEdgelist <- data.frame()

    submulti <-
      multilayerEdges[multilayerEdges$node.from == multilayerEdges$node.to,]
    
    Inter <- data.frame(
          from = submulti$layer.from,
          node = submulti$node.from,
          to = submulti$layer.to,
          weight = submulti$weight
        ) %>%
      .[.$from != .$to,]
    
    mergedEdgelist <-
      rbind(
        mergedEdgelist,
        Inter
      )
    if (!isDirected) {
      Inter <- data.frame(
            from = submulti$layer.to,
            node = submulti$node.from,
            to = submulti$layer.from,
            weight = submulti$weight
          ) %>%
      .[.$from != .$to,]
      #this is because multimap requires both directions specified, even for undirected networks
      mergedEdgelist <-
        rbind(
          mergedEdgelist,
          Inter
        )
    }
    mergedEdgelist <- mergedEdgelist
    utils::write.table(
      mergedEdgelist,
      file = fileConn,
      row.names = F,
      col.names = F,
      quote = F
    )

    close(fileConn)

    cat('2/2 Finding communities...\n')
    cat(' + Multiplex network...\n')

    exePath <- bin.path

    outname <- tmpname
    outdir <- getwd()

    #default flags
    exeFlags <- paste(inputFile, outdir)
    exeFlags <- paste(exeFlags, "--input-format multilayer")
    exeFlags <- paste(exeFlags, "--clu --map --tree --expanded")

    exeFlags <- paste(exeFlags, "--seed", seed)
    exeFlags <- paste(exeFlags, "--num-trials", numTrials)

    if (isDirected) {
      exeFlags <- paste(exeFlags, "-d")
    } else {
      exeFlags <- paste(exeFlags, "-u")
    }

    if (includeSelfLinks) {
      exeFlags <- paste(exeFlags, "--include-self-links")
    }

    if (twoLevel) {
      exeFlags <- paste(exeFlags, "--two-level")
    }

    if (preclusterMultiplex) {
      exeFlags <- paste(exeFlags, "--pre-cluster-multiplex")
    }

    if (addMissingPhysicalNodes) {
      exeFlags <- paste(exeFlags, "--multilayer-add-missing-nodes")
    }

    if (hardPartitions) {
      exeFlags <- paste(exeFlags, "--hard-partitions")
    }

    if (verbose) {
      exeFlags <- paste(exeFlags, "-vvv")
    }

    exeFlags <- paste(exeFlags, "--out-name", outname)

    #call infomap
    system(paste(exePath, exeFlags), intern = T)


    #read output. Here I could redirect the output inside the R environment.. but
    #for compatibility with the rest of the code I prefer to read a file
    communityList <- list()

    #import the results (clu and modularity value)
    resultFile <- paste0(outputPrefix, "_expanded.clu")
    wmemb_membership <- utils::read.table(resultFile, header = F, sep = " ")

    communityList$membership.multi <- wmemb_membership

    #if(!hardPartitions){
    #same columns regardless of this flag
    colnames(communityList$membership.multi) <-
      c("layer", "node", "module", "flow")
    #}
    #reorder, for easier inspection
    communityList$membership.multi <-
      communityList$membership.multi[order(communityList$membership.multi$layer,
                                           communityList$membership.multi$node), ]


    resultFile <- paste0(outputPrefix, "_expanded.map")
    wtcod <-
      as.numeric(strsplit(readLines(resultFile, n = 5), " ")[[5]][3])

    communityList$codelength.multi <- wtcod

    cat(paste("    Code length Multiplex: ", wtcod, "\n"))
    numComms <- max(wmemb_membership$V3)
    cat(paste("    Communities Multiplex: ", numComms, "\n"))

    communityList$modules.multi <- numComms

    communityList$msize.multi <-
      table(communityList$membership.multi$module)

    #depending on flags, Infomap can transform into layer IDs the id of isolated nodes.
    #let's remove those ones
    communityList$membership.multi <-
      communityList$membership.multi[which(communityList$membership.multi$layer <=
                                             Layers), ]

    #TODO for the future: calculate modularity of the partition. No direct multiplex way from igraph
    #one possibility is to pass the expanded representation of the network
    #but in case of edgecolored the supradjacency matrix would empty off-diagonal
    #resulting in huge modularity due to layers, not modules..
    #igraph::modularity(x, membership, weights = NULL, ...)

    if (addAggregateAnalysis) {
      cat(' + Aggregate network...\n')

      #calculate same things for the aggregate using R-igraph infomap
      g.agg <-
        GetAggregateNetworkFromSupraAdjacencyMatrix(SupraAdjacencyMatrix, Layers, Nodes)

      infocom <-
        igraph::cluster_infomap(g.agg, modularity = TRUE)
      wmemb_membership_aggregate <-
        as.numeric(igraph::membership(infocom))
      wtcod_aggregate <- igraph::code_len(infocom)

      communityList$membership.aggr <-
        data.frame(node = 1:length(wmemb_membership_aggregate),
                   module = wmemb_membership_aggregate)
      communityList$codelength.aggr <- wtcod_aggregate

      cat(paste("    Code length Aggregate: ", wtcod_aggregate, "\n"))
      numCommsAggr <- max(wmemb_membership_aggregate)
      cat(paste("    Communities Aggregate: ", numCommsAggr, "\n"))

      communityList$modules.aggr <- numCommsAggr
      communityList$msize.aggr <-
        table(communityList$membership.aggr$module)
    }

    cat('Calculation Completed!\n')

    return(communityList)
  }
```


```{r}
commResult2 <-
  GetMultilayerCommunities_Infomap_modified(
    SupraAdjacencyMatrix = M,
    Layers = Layers,
    Nodes = Nodes,
    bin.path = pathInfomap,
    isDirected = T,
    seed = 12345,
    includeSelfLinks = T,
    numTrials = 100,
    twoLevel = T,
    preclusterMultiplex = F,
    addMissingPhysicalNodes = F,
    hardPartitions = F,
    verbose = T,
    addAggregateAnalysis = T,
    outputPrefix = "multimap_example2"
  )
```

```{r}
# coloring state nodes
node.colors.matrix2 <- matrix("#dadada", Nodes, Layers)
for(l in 1:Layers){
    dftmp <- commResult2$membership.multi[commResult2$membership.multi$layer==l,]
    idxs <- dftmp$node
    node.colors.matrix2[idxs,l] <- pal.mux[dftmp$module]
}

# coloring physical nodes in the aggregate
node.colors.aggr2 <- rep("#dadada", Nodes)
node.colors.aggr2[commResult2$membership.aggr$node] <- pal.aggr[commResult2$membership.aggr$module]

plot_multiplex3D(Multiplex_test$g.list, layer.layout=lay, layer.colors=layer.colors,
                         layer.shift.x=0.5, layer.space=2,
                         layer.labels="auto", layer.labels.cex=1.5,
                         node.size.values="auto", node.size.scale=0.8,
                         node.colors=node.colors.matrix2, edge.colors="#dadada",
                         node.colors.aggr=node.colors.aggr2,
                         show.aggregate=T)
rgl::snapshot3d("Results/multi_sbm_infomap2.png", fmt="png", width = 1024, height = 1024)
#> Warning in snapshot3d("../man/figures/multi_sbm_infomap2.png", fmt = "png", :
#> webshot = TRUE requires the webshot2 package; using rgl.snapshot() instead
```

